services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8080
    volumes:
      - type: bind
        source: ./data
        target: /data
    networks:
      - calc-net

  worker1:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - orchestrator
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8080
    networks:
      - calc-net

  worker2:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - orchestrator
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8080
    networks:
      - calc-net

volumes:
  data:

networks:
  calc-net: