services:
  calc_service:
    build: .
    command: /app/calc_service
    ports:
      - "8080:8080"
      - "50051:50051"

  worker:
    build: .
    command: /app/worker
    environment:
      - ORCHESTRATOR_GRPC_URL=calc_service:50051